### ISSUE TITLE
Global Singleton Pool

### ISSUE THREAD

**Issue by LiboShen** [phoenixframework/flame#29]
I'm using FLAME for my project to run ML workload running on Fly.

Because initialing a model with Bumblebee could take minutes, I set the min runner to 1, and hope there is always 1 runner node live.

However, I have 2 web serving nodes (clustered), and during the starting up both of them were trying to create a new Fly machine.

Could we add a `:global` option in the Pool config, and make the Pool global within a cluster Like:

```elixir
{FLAME.Pool,
      name: Thumbs.FFMpegRunner,
      min: 0,
      max: 10,
      max_concurrency: 5,
      idle_shutdown_after: 30_000,
      global: true},
```

**Comment by chrismccord** [comment]
The way flame works by design is to avoid global coordination. The parent node manages its own flame children to avoid any orchestration layer as well as guarantees that the child is spawned as close as possible to the parent node (same datacenter worst case, same physical server best case). If you want to to have a single global FLAME child instance for a pool, you’d need to add the orchestration layer yourself.

For example, you could hardcode one of your machines to be the “primary” and start the flame pool only for that machine ID, then other nodes RPC the primary to perform the flame calls (see :erpc), or in the case of Nx.Serving, it should Just Work because Nx does its own distributed progress group. Or you could come up with other strategies to elect the leader and start the pool on demand (all with their own tradeoffs). Also if you are going multi-region, then you’d pay the cost to send data back and forth to the FLAME instances and added coordination brings a bunch of failure mode considerations.

I won't rule out distributed pool features for the future, but it's not something planned anytime soon and comes with its own set of tradeoffs and a ton of complexity. Thanks!
